### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#109]
@rfk do you know which freezers work with pypy? I want to add some documentation in this area.

**Comment by rfk** [comment]
I don't sorry; I've never tried to make a frozen app with pypy as its interpreter.

(The code in esky can use pypy for compiling its bootstrap env, but that's a while 'nother story and I'm not at all sure it still works with latest upstream pypy)

**Comment by timeyyy** [comment]
So if you have pypy installed esky will try and compile the bootstrap.env with pypy? Is the purpose of this to increase speed? Is this a useful feature we should support/ document?

**Comment by rfk** [comment]
> So if you have pypy installed esky will try and compile the bootstrap.env with pypy

There's a special option in setup.py to enable it, something like `compile_bootstrap_exe`.

> Is the purpose of this to increase speed?

Mostly it's to decrease file size; it means you can have just a very small stub exe in the bootstrap env, rather than a copy of a whole python interpreter.

> Is this a useful feature we should support/ document?

Yes, but first we should confirm whether it still works at all :-)

**Comment by rfk** [comment]
Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
