### ISSUE TITLE
Support for Pyinstaller

### ISSUE THREAD

**Issue by prathaps** [cloudmatrix/esky#18]
Hi,

Really cool auto update framework! I have a python project that is frozen using py2app for mac and pyinstaller for windows:

1) Does esky support Pyinstaller? If not, is it hard to extend it it to support Pyinstaller? I am not familiar with pyinstaller so if you can point me to any resources on how I could look into extending it, that would be awesome.

2) The biggest reason we chose pyinstaller over py2exe is because of lack of code signing support in py2exe. Esky would be easier choice if there was another easy way to make a py2exe executable code signed but I am not aware of it. If you are aware of how I could make this work, some pointers there would be appreciated.

Thanks!

**Comment by leycec** [comment]
For all long-standing bystanders to this discussion, **the chosen day has arrived.** Meet [updater4pyi](https://pypi.python.org/pypi/updater4pyi), a [well-documented](http://updater4pyi.readthedocs.org/en/latest) [open-source](https://github.com/phfaist/updater4pyi) nearly-pure-Python solution for auto-updating cross-platform-portable Python applications frozen with PyInstaller. (github's been holding out on us, folks.)

There appear to be at least two – but probably more, as of your reading this – open-source projects already leveraging updater4pyi in a meaningful way: [MCEdit-Unified](https://github.com/Khroki/MCEdit-Unified) and [bibolamazi](https://github.com/phfaist/bibolamazi). Regardless of whether you care about Minecraft or not (_admits it!_), the [hook-updater4pyi.py](https://github.com/Khroki/MCEdit-Unified/blob/master/hook-updater4pyi.py) script shipped with MCEdit-Unified should give you a giddy inkling of updater4pyi's ease of use. **[Hint:** it's easy to use.**]**

While I personally have yet to use updater4pyi, I'm greedily contemplating it. Because let's face it: esky-based PyInstaller support is just _not_ in the cards, folks.

**Comment by JohnyMoSwag** [comment]
You can also check out my auto update framework. [PyiUpdater](https://github.com/JohnyMoSwag/PyiUpdater) currently still in beta. Only supports onefile mode with pyinstaller, but has the ability to also update support files.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
