### ISSUE TITLE
Created exe does not work (Python 3.4, py2exe, Win7 x64)

### ISSUE THREAD

**Issue by sergeyfarin** [cloudmatrix/esky#72]
Used example script (see below)
Created exe file and zip file; however, created file does not work. Gives error message

![image](https://cloud.githubusercontent.com/assets/1467219/4503287/cfa4d190-4ad5-11e4-8dc6-fd1a2e28d0db.png)

		import sys
		from esky import bdist_esky
		import py2exe

		from esky.bdist_esky import Executable
		from distutils.core import setup

		sys.argv.append('bdist_esky')
		# for windows
		# > python setup.py bdist_esky
		if sys.platform in ['win32','cygwin','win64']:

			# Use bdist_esky instead of py2exe

			setup(
				name = "example-app",
				version = "0.1",
				#  All executables are listed in the "scripts" argument
				scripts = ["example.py"],
				options = {"bdist_esky": {
						  "freezer_module":"py2exe"
						  }
						}
			)

		# for mac
		# > python setup.py bdist_esky
		elif sys.platform == 'darwin':
			setup(
				name = "example-app",
				version = "0.1",
				scripts = ["example.py"],
				options = {"bdist_esky": {
							"freezer_module":"py2app"
						 }}
			)

**Comment by scriptdeez** [comment]
Hi Sergey,

I had the same issues, using the same setup, with my application. 

The resolution, in my case, was to use the latest edition of cx_freeze instead of Py2exe. .NET msvcr100.dll was crashing, according to the minidump, and lead me to the creation of the bootstrap, which relies heavily on the freezing module being used.

I hope this helps!

**Comment by mvbentes** [comment]
I have the same problem. The real executable under the distribution folder runs fine. It is just the esky executable that has this problem.
I have been looking for the point in the code where it was made into a excutable but could not find it. Could it be because the bootstrap has to be in Rpython and encodings is not built-in?

Scriptdeez, could you provide the code you used to solve it on your end?

Thanks.
