### ISSUE TITLE
Support code sign on Mac OS X

### ISSUE THREAD

**Issue by jiakuan** [cloudmatrix/esky#74]
First of all, I would like to say esky is awesome! I have used it successfully in our Python app which is developed for both Mac and Windows. The auto-update function provided by Esky works perfectly.

Recently we had to codesign the Mac app, and I realized that the appdata folder inside the XXX.app file is not following the standard folder structure, hence  the esky app couldn't be signed via codesign command. Also for a signed app, it may not be possible to write files inside the XXX.app folder when auto-updating.

I'm thinking if it is possible to do the auto-download in an external folder (e.g ~/Library/Application Support/MyApp/update/), and then copy and replace the whole new signed app to install the new version automatically? Or, is there a better way to support code sign for Mac?

**Comment by stephanelsmith** [comment]
Have this exact issue as well.  Would be nice to if esky ESKY_CONTROL_DIR and ESKY_APPDATA_DIR maybe pointed to x.app/Contents/Resources/.  Not sure if that would help.

Not a Mac expert.  I'm just not supporting esky on osx for now since I can't sign code with esky included.

**Comment by rfk** [comment]
Sadly, I probably won't find time to work on this, but would be happy to accept patches and help with testing etc.  The suggested re-structuring sounds OK to me at first glance, the only tricky part might be ensuring that that the external updates folder is on the same filesystem as the app, so that atomic renames work correctly.

I don't know much about codesigning on the mac these days (I know I succesfully code-signed an esky bundle many years ago, but things have probably changed since then).  Can you go into any more detail about where and why the current layout fails?

**Comment by jiakuan** [comment]
I have to disable esky for Mac app for now as well. Currently the 'appdata' folder is in the root directory of a Mac app, e.g. XXX.app/appdata, I guess it may resolve the issue if we put it in XXX.app/Contents/Resources. But when updating, not sure if we can just change some of the files in the signed app.

**Comment by mherrmann** [comment]
Sorry to chime in but I'm having trouble getting Esky to produce a `.app` in the first place. @jiakuan how did you do this? I described my problems in a question [on StackOverflow](http://stackoverflow.com/questions/37818567/create-app-dmg-with-esky). If anyone could help with this, that would be awesome. Sorry again for hijacking this issue with a (somewhat) unrelated question.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
